### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for CifarResNeXt:

### ISSUE THREAD

**Issue by ma3252788** [prlz77/ResNeXt.pytorch#19]
When I try to run test.py , I got this:

```bash
Traceback (most recent call last):
  File "/home/ubuntu/bigdisk/part1/resnext.pytorch/test.py", line 114, in <module>
    test()
  File "/home/ubuntu/bigdisk/part1/resnext.pytorch/test.py", line 79, in test
    net.load_state_dict(loaded_state_dict)
  File "/home/ubuntu/anaconda3/envs/resnext/lib/python2.7/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for CifarResNeXt:
	Missing key(s) in state_dict: "conv_1_3x3.weight", "bn_1.running_var", "bn_1.bias", "bn_1.weight", "bn_1.running_mean", "stage_1.stage_1_bottleneck_0.conv_reduce.weight", "stage_1.stage_1_bottleneck_0.bn_reduce.running_var", "stage_1.stage_1_bottleneck_0.bn_reduce.bias", "stage_1.stage_1_bottleneck_0.bn_reduce.weight", "stage_1.stage_1_bottleneck_0.bn_reduce.running_mean", "stage_1.stage_1_bottleneck_0.conv_conv.weight", "stage_1.stage_1_bottleneck_0.bn.running_var", "stage_1.stage_1_bottleneck_0.bn.bias", "stage_1.stage_1_bottleneck_0.bn.weight", "stage_1.stage_1_bottleneck_0.bn.running_mean", "stage_1.stage_1_bottleneck_0.conv_expand.weight", "stage_1.stage_1_bottleneck_0.bn_expand.running_var", "stage_1.stage_1_bottleneck_0.bn_expand.bias", "stage_1.stage_1_bottleneck_0.bn_expand.weight", "stage_1.stage_1_bottleneck_0.bn_expand.running_mean", "stage_1.stage_1_bottleneck_0.shortcut.shortcut_conv.weight", "stage_1.stage_1_bottleneck_0.shortcut.shortcut_bn.running_var", "stage_1.stage_1_bottleneck_0.shortcut.shortcut_bn.bias", "stage_1.stage_1_bottleneck_0.shortcut.shortcut_bn.weight", "stage_1.stage_1_bottleneck_0.shortcut.shortcut_bn.running_mean", "stage_1.stage_1_bottleneck_1.conv_reduce.weight", "stage_1.stage_1_bottleneck_1.bn_reduce.running_var", "stage_1.stage_1_bottleneck_1.bn_reduce.bias", "stage_1.stage_1_bottleneck_1.bn_reduce.weight", "stage_1.stage_1_bottleneck_1.bn_reduce.running_mean", "stage_1.stage_1_bottleneck_1.conv_conv.weight", "stage_1.stage_1_bottleneck_1.bn.running_var", "stage_1.stage_1_bottleneck_1.bn.bias", "stage_1.stage_1_bottleneck_1.bn.weight", "stage_1.stage_1_bottleneck_1.bn.running_mean", "stage_1.stage_1_bottleneck_1.conv_expand.weight", "stage_1.stage_1_bottleneck_1.bn_expand.running_var", "stage_1.stage_1_bottleneck_1.bn_expand.bias", "stage_1.stage_1_bottleneck_1.bn_expand.weight", "stage_1.stage_1_bottleneck_1.bn_expand.running_mean", "stage_1.stage_1_bottleneck_2.conv_reduce.weight", "stage_1.stage_1_bottleneck_2.bn_reduce.running_var", "stage_1.stage_1_bottleneck_2.bn_reduce.bias", "stage_1.stage_1_bottleneck_2.bn_reduce.weight", "stage_1.stage_1_bottleneck_2.bn_reduce.running_mean", "stage_1.stage_1_bottleneck_2.conv_conv.weight", "stage_1.stage_1_bottleneck_2.bn.running_var", "stage_1.stage_1_bottleneck_2.bn.bias", "stage_1.stage_1_bottleneck_2.bn.weight", "stage_1.stage_1_bottleneck_2.bn.running_mean", "stage_1.stage_1_bottleneck_2.conv_expand.weight", "stage_1.stage_1_bottleneck_2.bn_expand.running_var", "stage_1.stage_1_bottleneck_2.bn_expand.bias", "stage_1.stage_1_bottleneck_2.bn_expand.weight", "stage_1.stage_1_bottleneck_2.bn_expand.running_mean", "stage_2.stage_2_bottleneck_0.conv_reduce.weight", "stage_2.stage_2_bottleneck_0.bn_reduce.running_var", "stage_2.stage_2_bottleneck_0.bn_reduce.bias", "stage_2.stage_2_bottleneck_0.bn_reduce.weight", "stage_2.stage_2_bottleneck_0.bn_reduce.running_mean", "stage_2.stage_2_bottleneck_0.conv_conv.weight", "stage_2.stage_2_bottleneck_0.bn.running_var", "stage_2.stage_2_bottleneck_0.bn.bias", "stage_2.stage_2_bottleneck_0.bn.weight", "stage_2.stage_2_bottleneck_0.bn.running_mean", "stage_2.stage_2_bottleneck_0.conv_expand.weight", "stage_2.stage_2_bottleneck_0.bn_expand.running_var", "stage_2.stage_2_bottleneck_0.bn_expand.bias", "stage_2.stage_2_bottleneck_0.bn_expand.weight", "stage_2.stage_2_bottleneck_0.bn_expand.running_mean", "stage_2.stage_2_bottleneck_0.shortcut.shortcut_conv.weight", "stage_2.stage_2_bottleneck_0.shortcut.shortcut_bn.running_var", "stage_2.stage_2_bottleneck_0.shortcut.shortcut_bn.bias", "stage_2.stage_2_bottleneck_0.shortcut.shortcut_bn.weight", "stage_2.stage_2_bottleneck_0.shortcut.shortcut_bn.running_mean", "stage_2.stage_2_bottleneck_1.conv_reduce.weight", "stage_2.stage_2_bottleneck_1.bn_reduce.running_var", "stage_2.stage_2_bottleneck_1.bn_reduce.bias", "stage_2.stage_2_bottleneck_1.bn_reduce.weight", "stage_2.stage_2_bottleneck_1.bn_reduce.running_mean", "stage_2.stage_2_bottleneck_1.conv_conv.weight", "stage_2.stage_2_bottleneck_1.bn.running_var", "stage_2.stage_2_bottleneck_1.bn.bias", "stage_2.stage_2_bottleneck_1.bn.weight", "stage_2.stage_2_bottleneck_1.bn.running_mean", "stage_2.stage_2_bottleneck_1.conv_expand.weight", "stage_2.stage_2_bottleneck_1.bn_expand.running_var", "stage_2.stage_2_bottleneck_1.bn_expand.bias", "stage_2.stage_2_bottleneck_1.bn_expand.weight", "stage_2.stage_2_bottleneck_1.bn_expand.running_mean", "stage_2.stage_2_bottleneck_2.conv_reduce.weight", "stage_2.stage_2_bottleneck_2.bn_reduce.running_var", "stage_2.stage_2_bottleneck_2.bn_reduce.bias", "stage_2.stage_2_bottleneck_2.bn_reduce.weight", "stage_2.stage_2_bottleneck_2.bn_reduce.running_mean", "stage_2.stage_2_bottleneck_2.conv_conv.weight", "stage_2.stage_2_bottleneck_2.bn.running_var", "stage_2.stage_2_bottleneck_2.bn.bias", "stage_2.stage_2_bottleneck_2.bn.weight", "stage_2.stage_2_bottleneck_2.bn.running_mean", "stage_2.stage_2_bottleneck_2.conv_expand.weight", "stage_2.stage_2_bottleneck_2.bn_expand.running_var", "stage_2.stage_2_bottleneck_2.bn_expand.bias", "stage_2.stage_2_bottleneck_2.bn_expand.weight", "stage_2.stage_2_bottleneck_2.bn_expand.running_mean", "stage_3.stage_3_bottleneck_0.conv_reduce.weight", "stage_3.stage_3_bottleneck_0.bn_reduce.running_var", "stage_3.stage_3_bottleneck_0.bn_reduce.bias", "stage_3.stage_3_bottleneck_0.bn_reduce.weight", "stage_3.stage_3_bottleneck_0.bn_reduce.running_mean", "stage_3.stage_3_bottleneck_0.conv_conv.weight", "stage_3.stage_3_bottleneck_0.bn.running_var", "stage_3.stage_3_bottleneck_0.bn.bias", "stage_3.stage_3_bottleneck_0.bn.weight", "stage_3.stage_3_bottleneck_0.bn.running_mean", "stage_3.stage_3_bottleneck_0.conv_expand.weight", "stage_3.stage_3_bottleneck_0.bn_expand.running_var", "stage_3.stage_3_bottleneck_0.bn_expand.bias", "stage_3.stage_3_bottleneck_0.bn_expand.weight", "stage_3.stage_3_bottleneck_0.bn_expand.running_mean", "stage_3.stage_3_bottleneck_0.shortcut.shortcut_conv.weight", "stage_3.stage_3_bottleneck_0.shortcut.shortcut_bn.running_var", "stage_3.stage_3_bottleneck_0.shortcut.shortcut_bn.bias", "stage_3.stage_3_bottleneck_0.shortcut.shortcut_bn.weight", "stage_3.stage_3_bottleneck_0.shortcut.shortcut_bn.running_mean", "stage_3.stage_3_bottleneck_1.conv_reduce.weight", "stage_3.stage_3_bottleneck_1.bn_reduce.running_var", "stage_3.stage_3_bottleneck_1.bn_reduce.bias", "stage_3.stage_3_bottleneck_1.bn_reduce.weight", "stage_3.stage_3_bottleneck_1.bn_reduce.running_mean", "stage_3.stage_3_bottleneck_1.conv_conv.weight", "stage_3.stage_3_bottleneck_1.bn.running_var", "stage_3.stage_3_bottleneck_1.bn.bias", "stage_3.stage_3_bottleneck_1.bn.weight", "stage_3.stage_3_bottleneck_1.bn.running_mean", "stage_3.stage_3_bottleneck_1.conv_expand.weight", "stage_3.stage_3_bottleneck_1.bn_expand.running_var", "stage_3.stage_3_bottleneck_1.bn_expand.bias", "stage_3.stage_3_bottleneck_1.bn_expand.weight", "stage_3.stage_3_bottleneck_1.bn_expand.running_mean", "stage_3.stage_3_bottleneck_2.conv_reduce.weight", "stage_3.stage_3_bottleneck_2.bn_reduce.running_var", "stage_3.stage_3_bottleneck_2.bn_reduce.bias", "stage_3.stage_3_bottleneck_2.bn_reduce.weight", "stage_3.stage_3_bottleneck_2.bn_reduce.running_mean", "stage_3.stage_3_bottleneck_2.conv_conv.weight", "stage_3.stage_3_bottleneck_2.bn.running_var", "stage_3.stage_3_bottleneck_2.bn.bias", "stage_3.stage_3_bottleneck_2.bn.weight", "stage_3.stage_3_bottleneck_2.bn.running_mean", "stage_3.stage_3_bottleneck_2.conv_expand.weight", "stage_3.stage_3_bottleneck_2.bn_expand.running_var", "stage_3.stage_3_bottleneck_2.bn_expand.bias", "stage_3.stage_3_bottleneck_2.bn_expand.weight", "stage_3.stage_3_bottleneck_2.bn_expand.running_mean", "classifier.bias", "classifier.weight". 
	Unexpected key(s) in state_dict: ".stage_1_bottleneck_0.bn.num_batches_tracked", ".stage_1_bottleneck_2.bn.bias", ".stage_1_bottleneck_1.bn_expand.bias", ".stage_2_bottleneck_0.shortcut.shortcut_bn.num_batches_tracked", ".stage_2_bottleneck_0.bn_expand.running_var", ".stage_2_bottleneck_1.bn_expand.bias", ".stage_3_bottleneck_0.bn_expand.running_mean", ".stage_3_bottleneck_2.bn.bias", ".stage_3_bottleneck_0.bn_reduce.weight", ".stage_2_bottleneck_0.bn.weight", ".stage_2_bottleneck_0.bn.running_mean", ".stage_2_bottleneck_0.shortcut.shortcut_bn.running_mean", ".stage_3_bottleneck_0.bn_reduce.num_batches_tracked", ".stage_2_bottleneck_1.bn_expand.running_mean", ".stage_2_bottleneck_0.bn.num_batches_tracked", ".stage_2_bottleneck_2.conv_expand.weight", ".stage_1_bottleneck_2.bn_expand.weight", ".stage_2_bottleneck_1.bn_expand.weight", ".stage_2_bottleneck_0.bn_reduce.running_var", ".stage_1_bottleneck_2.bn_expand.running_var", ".stage_1_bottleneck_0.bn.running_mean", ".stage_1_bottleneck_0.bn_reduce.running_var", ".stage_1_bottleneck_0.bn_reduce.weight", ".stage_2_bottleneck_1.bn.running_var", "ight", ".stage_2_bottleneck_2.bn_reduce.running_var", ".stage_2_bottleneck_0.bn_reduce.num_batches_tracked", ".stage_3_bottleneck_0.bn.running_mean", ".stage_2_bottleneck_2.bn_expand.running_var", ".stage_1_bottleneck_0.conv_reduce.weight", ".stage_2_bottleneck_1.bn_reduce.weight", ".stage_1_bottleneck_1.bn_expand.num_batches_tracked", ".stage_2_bottleneck_2.bn_reduce.weight", ".stage_3_bottleneck_0.shortcut.shortcut_bn.bias", ".stage_3_bottleneck_2.bn.weight", ".stage_1_bottleneck_1.bn.running_var", ".stage_1_bottleneck_1.bn_reduce.weight", ".stage_1_bottleneck_0.bn_expand.weight", ".stage_2_bottleneck_2.conv_conv.weight", ".stage_1_bottleneck_1.bn_expand.running_mean", ".stage_2_bottleneck_0.bn_expand.bias", ".stage_2_bottleneck_1.bn.bias", ".stage_3_bottleneck_1.bn_expand.num_batches_tracked", ".stage_2_bottleneck_2.bn.num_batches_tracked", ".stage_1_bottleneck_2.conv_conv.weight", ".stage_3_bottleneck_0.conv_conv.weight", ".stage_2_bottleneck_1.bn_reduce.running_var", ".stage_1_bottleneck_1.bn_expand.weight", ".stage_3_bottleneck_0.bn_expand.weight", ".stage_1_bottleneck_1.bn.weight", ".stage_3_bottleneck_0.bn.weight", ".stage_3_bottleneck_2.bn_reduce.weight", ".stage_1_bottleneck_2.bn.weight", ".stage_2_bottleneck_0.bn_expand.weight", ".stage_2_bottleneck_0.shortcut.shortcut_bn.weight", ".stage_1_bottleneck_2.bn.running_mean", ".stage_1_bottleneck_0.bn.weight", "nning_mean", ".stage_1_bottleneck_0.shortcut.shortcut_bn.running_var", ".stage_3_bottleneck_1.conv_reduce.weight", ".stage_2_bottleneck_2.bn_expand.num_batches_tracked", ".stage_2_bottleneck_2.bn_expand.weight", ".stage_1_bottleneck_2.bn_reduce.bias", ".stage_3_bottleneck_2.bn_reduce.num_batches_tracked", ".stage_1_bottleneck_1.conv_expand.weight", ".stage_3_bottleneck_1.bn_expand.bias", ".stage_3_bottleneck_1.conv_conv.weight", ".stage_1_bottleneck_2.bn.num_batches_tracked", ".stage_3_bottleneck_0.shortcut.shortcut_conv.weight", ".stage_3_bottleneck_0.shortcut.shortcut_bn.num_batches_tracked", ".stage_3_bottleneck_1.bn.running_var", ".stage_2_bottleneck_2.bn.running_mean", ".stage_2_bottleneck_0.bn_expand.num_batches_tracked", ".stage_3_bottleneck_1.bn_reduce.num_batches_tracked", ".stage_3_bottleneck_0.bn.running_var", ".stage_2_bottleneck_1.bn_reduce.running_mean", ".stage_3_bottleneck_0.shortcut.shortcut_bn.weight", ".stage_1_bottleneck_0.bn.bias", ".stage_1_bottleneck_2.bn_reduce.weight", ".stage_3_bottleneck_0.conv_expand.weight", ".stage_1_bottleneck_0.bn_reduce.num_batches_tracked", ".stage_3_bottleneck_2.bn.running_var", ".stage_3_bottleneck_2.conv_conv.weight", ".stage_3_bottleneck_2.bn_expand.running_var", ".stage_1_bottleneck_1.bn.num_batches_tracked", ".stage_3_bottleneck_0.bn.bias", ".stage_3_bottleneck_0.bn_reduce.running_mean", ".stage_2_bottleneck_0.bn_reduce.bias", ".stage_1_bottleneck_0.shortcut.shortcut_conv.weight", ".stage_2_bottleneck_2.bn.weight", ".stage_1_bottleneck_0.shortcut.shortcut_bn.running_mean", ".stage_3_bottleneck_1.bn_reduce.running_var", ".stage_2_bottleneck_0.bn_expand.running_mean", ".stage_2_bottleneck_1.bn_reduce.num_batches_tracked", ".stage_2_bottleneck_1.conv_reduce.weight", ".stage_2_bottleneck_0.bn_reduce.running_mean", ".stage_1_bottleneck_1.bn_expand.running_var", ".stage_1_bottleneck_1.bn_reduce.running_var", ".stage_3_bottleneck_1.bn_reduce.running_mean", ".stage_2_bottleneck_0.shortcut.shortcut_bn.bias", ".stage_2_bottleneck_2.bn_expand.running_mean", "ier.bias", ".stage_3_bottleneck_0.bn_expand.num_batches_tracked", ".stage_2_bottleneck_1.bn_expand.running_var", ".stage_3_bottleneck_0.bn_expand.bias", "3x3.weight", ".stage_3_bottleneck_1.bn.weight", ".stage_2_bottleneck_0.bn.bias", ".stage_1_bottleneck_0.shortcut.shortcut_bn.weight", ".stage_1_bottleneck_2.bn.running_var", ".stage_2_bottleneck_2.bn.bias", ".stage_2_bottleneck_2.conv_reduce.weight", ".stage_1_bottleneck_0.bn.running_var", ".stage_3_bottleneck_2.bn_expand.num_batches_tracked", ".stage_3_bottleneck_1.bn.num_batches_tracked", ".stage_1_bottleneck_0.bn_expand.running_mean", ".stage_3_bottleneck_1.bn_reduce.bias", ".stage_2_bottleneck_2.bn_expand.bias", ".stage_3_bottleneck_1.bn.bias", ".stage_2_bottleneck_2.bn_reduce.bias", ".stage_2_bottleneck_0.conv_conv.weight", ".stage_1_bottleneck_2.bn_expand.num_batches_tracked", ".stage_1_bottleneck_1.bn.bias", ".stage_2_bottleneck_1.bn.weight", ".stage_2_bottleneck_2.bn.running_var", ".stage_3_bottleneck_0.bn.num_batches_tracked", ".stage_1_bottleneck_0.conv_expand.weight", ".stage_1_bottleneck_1.conv_reduce.weight", ".stage_3_bottleneck_2.bn_expand.weight", ".stage_2_bottleneck_1.conv_conv.weight", ".stage_1_bottleneck_1.bn_reduce.num_batches_tracked", ".stage_1_bottleneck_2.bn_expand.bias", ".stage_2_bottleneck_1.conv_expand.weight", ".stage_3_bottleneck_0.conv_reduce.weight", ".stage_1_bottleneck_0.bn_expand.num_batches_tracked", ".stage_2_bottleneck_1.bn_expand.num_batches_tracked", ".stage_3_bottleneck_2.conv_expand.weight", ".stage_2_bottleneck_1.bn.num_batches_tracked", "ier.weight", ".stage_3_bottleneck_2.bn_expand.bias", ".stage_3_bottleneck_2.bn_reduce.bias", ".stage_3_bottleneck_2.bn.num_batches_tracked", ".stage_1_bottleneck_2.conv_expand.weight", "as", ".stage_2_bottleneck_2.bn_reduce.num_batches_tracked", ".stage_1_bottleneck_2.conv_reduce.weight", ".stage_3_bottleneck_1.conv_expand.weight", ".stage_3_bottleneck_2.conv_reduce.weight", ".stage_2_bottleneck_0.bn_reduce.weight", ".stage_3_bottleneck_0.shortcut.shortcut_bn.running_mean", ".stage_1_bottleneck_0.bn_reduce.bias", ".stage_1_bottleneck_2.bn_reduce.running_mean", ".stage_2_bottleneck_1.bn.running_mean", ".stage_1_bottleneck_0.shortcut.shortcut_bn.bias", ".stage_3_bottleneck_0.bn_reduce.running_var", "m_batches_tracked", ".stage_1_bottleneck_0.bn_expand.bias", ".stage_1_bottleneck_2.bn_expand.running_mean", ".stage_3_bottleneck_0.bn_expand.running_var", ".stage_2_bottleneck_0.conv_expand.weight", ".stage_2_bottleneck_0.bn.running_var", ".stage_3_bottleneck_1.bn_expand.weight", ".stage_1_bottleneck_1.bn.running_mean", ".stage_3_bottleneck_2.bn.running_mean", ".stage_3_bottleneck_2.bn_expand.running_mean", ".stage_1_bottleneck_0.conv_conv.weight", ".stage_3_bottleneck_1.bn_expand.running_mean", ".stage_2_bottleneck_0.conv_reduce.weight", ".stage_2_bottleneck_1.bn_reduce.bias", ".stage_1_bottleneck_0.bn_reduce.running_mean", ".stage_1_bottleneck_2.bn_reduce.running_var", ".stage_1_bottleneck_0.shortcut.shortcut_bn.num_batches_tracked", ".stage_1_bottleneck_2.bn_reduce.num_batches_tracked", ".stage_1_bottleneck_1.bn_reduce.running_mean", ".stage_3_bottleneck_1.bn_expand.running_var", ".stage_2_bottleneck_2.bn_reduce.running_mean", ".stage_3_bottleneck_0.shortcut.shortcut_bn.running_var", ".stage_3_bottleneck_2.bn_reduce.running_mean", "nning_var", ".stage_3_bottleneck_1.bn_reduce.weight", ".stage_3_bottleneck_2.bn_reduce.running_var", ".stage_2_bottleneck_0.shortcut.shortcut_conv.weight", ".stage_1_bottleneck_0.bn_expand.running_var", ".stage_2_bottleneck_0.shortcut.shortcut_bn.running_var", ".stage_3_bottleneck_0.bn_reduce.bias", ".stage_1_bottleneck_1.conv_conv.weight", ".stage_1_bottleneck_1.bn_reduce.bias", ".stage_3_bottleneck_1.bn.running_mean". 

Process finished with exit code 1

```

**Comment by prlz77** [comment]
Hey! I have fixed the problem. It turns out that the code to make it compatible with old pytorch weights has made it incompatible with the new ones. Thanks for pointing it out :)
